# Generated by Django 5.0.2 on 2024-02-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.AutoField(primary_key=True, serialize=False)),
                ("player_name", models.CharField(max_length=100)),
                ("player_photo", models.CharField(max_length=200)),
                ("player_type", models.CharField(max_length=20)),
                ("batting_average", models.FloatField()),
                ("strike_rate", models.FloatField()),
                ("rotating_strike", models.IntegerField()),
                ("boundary_percentage", models.FloatField()),
                ("bowling_average", models.FloatField()),
                ("economy_rate", models.FloatField()),
                ("wickets_taken", models.IntegerField()),
                ("catches", models.IntegerField()),
                ("dismissals", models.IntegerField()),
                ("missed_catches", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TeamPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="selector.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="selector.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="selector.team"
                    ),
                ),
            ],
        ),
    ]
