# Generated by Django 5.0.2 on 2024-02-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0002_alter_user_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
        migrations.CreateModel(
            name="UserTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_type",
                    models.CharField(
                        choices=[("T20", "T20"), ("ODI", "ODI"), ("TEST", "Test")],
                        max_length=4,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="selector.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="selector.user"
                    ),
                ),
            ],
        ),
    ]
