# Generated by Django 5.0.2 on 2024-02-15 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0003_remove_user_team_userteam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="team_name",
        ),
    ]
